### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jdom2/JDOMException (WORKAROUND)

### ISSUE THREAD

**Issue by lachlanodonnell** [jfrog/teamcity-artifactory-plugin#136]
Workaround by patching [jdom2-2.0.6.1.jar](https://repo1.maven.org/maven2/org/jdom/jdom2/2.0.6.1/jdom2-2.0.6.1.jar) into teamcity agent plugin's lib directory inside the teamcity plugin.

Using release process on TeamCity Professional 2022.10.2 (build 117025).   The following stack trace was produced. 

`java.lang.NoClassDefFoundError: org/jdom2/JDOMException
    at org.jfrog.teamcity.agent.listener.AgentListenerReleaseHelper.changePomVersions(AgentListenerReleaseHelper.java:139)
    at org.jfrog.teamcity.agent.listener.AgentListenerReleaseHelper.runnerFinished(AgentListenerReleaseHelper.java:90)
    at org.jfrog.teamcity.agent.ArtifactoryAgentListener.runnerFinished(ArtifactoryAgentListener.java:135)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:157)
    at jetbrains.buildServer.util.EventDispatcher.lambda$dispatch$0(EventDispatcher.java:134)
    at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
    at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:134)
    at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:82)
    at com.sun.proxy.$Proxy24.runnerFinished(Unknown Source)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.finish.FireRunnerFinishedFStage.doFinishStage(FireRunnerFinishedFStage.java:31)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.runFinishStage(RunnerFinishStagesExecutor.java:32)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.doBuildFinishStages(RunnerFinishStagesExecutor.java:23)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.safeCallFinishStages(RunnerContextExecutor.java:65)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:56)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:177)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:162)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:112)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:52)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:33)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:91)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:65)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:345)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:63)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:294)
    at java.base/java.lang.Thread.run(Thread.java:829)
  Caused by: java.lang.ClassNotFoundException: Class 'org.jdom2.JDOMException' was not found`

**Comment by mindruandrei3** [comment]
Hello,

I am facing the same issue with one Teamcity job.
Could you tell me exactly in which plugin directory did you copy the jdom2 library? I tried copying it in the build agent's home/library path and in the job's workspace directory but with no success.

Regards,
Andrei

**Comment by lachlanodonnell** [comment]
I did it originally by patching the artifactory teamcity plugin zip with the jar in the agent lib directory, then zipping with a new version number.  On my server the directory that jdom2 ended up in is:
![image](https://github.com/jfrog/teamcity-artifactory-plugin/assets/18819459/9c0010ac-85f4-477e-b1bd-ac74f32dc7c3)
