### ISSUE TITLE
Artifact resolving fails and NullPointerException thrown - TC 2018.1.2

### ISSUE THREAD

**Issue by daveneeley** [jfrog/teamcity-artifactory-plugin#54]
This seems to consistently happen on some agents.

Failed build
```[10:44:18]	TeamCity Artifactory Plugin version: 2.7.1
[10:44:19]	Starting: /sti/temp2/agentTmp/custom_script4524527879488291933
[10:44:19]	in directory: /sti/buildAgent2/work/6208045574d6b85d
[10:44:19]	downloading complete
[10:44:19]	Process exited with code 0
[10:44:19]	
[10:44:19]	
[10:44:19]	java.lang.NullPointerException
	at org.jfrog.teamcity.agent.ArtifactoryAgentListener.runnerFinished(ArtifactoryAgentListener.java:116)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:126)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:70)
	at $Proxy7.runnerFinished(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.finish.FireRunnerFinishedFStage.doFinishStage(FireRunnerFinishedFStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.runFinishStage(RunnerFinishStagesExecutor.java:32)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.doBuildFinishStages(RunnerFinishStagesExecutor.java:23)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.safeCallFinishStages(RunnerContextExecutor.java:65)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:56)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:300)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:54)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:264)
	at java.lang.Thread.run(Thread.java:736)

```

Successful build:

```[09:20:54]	TeamCity Artifactory Plugin version: 2.7.1
[09:20:54]	Beginning to resolve Build Info dependencies.
[09:20:54]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductA*/2019.1/*.war
[09:20:54]	Found 0 dependencies by doing a pattern search.
[09:20:54]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductB*/2019.1/*.war
[09:20:54]	Found 0 dependencies by doing a pattern search.
[09:20:54]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductC*/2019.1/*.war
[09:20:55]	Found 4 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductD*/2019.1/*.war
[09:20:55]	Found 0 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductE*/2019.1/*.war
[09:20:55]	Found 0 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductF*/2019.1/*.war
[09:20:55]	Found 1 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductG*/2019.1/*.war
[09:20:55]	Found 0 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductH*/2019.1/*.war
[09:20:55]	Found 1 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductI*/2019.1/*.war
[09:20:55]	Found 2 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductJ*/2019.1/*.war
[09:20:55]	Found 0 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductK*/2019.1/*.war
[09:20:55]	Found 1 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductL*/2019.1/*.war
[09:20:55]	Found 1 dependencies by doing a pattern search.
[09:20:55]	Resolving published dependencies with pattern domain-pilot-local:product/SubproductM*/2019.1/*.war
[09:20:55]	Found 1 dependencies by doing a pattern search.
[09:20:55]	Downloading 'https://artifactory.domain.com/artifactory/domain-pilot-local/product/Subproduct/2019.1/Subproduct.war'...
[09:20:58]	Successfully downloaded 'https://artifactory.domain.com/artifactory/domain-pilot-local/product/Subproduct/2019.1/Subproduct.war' to '/sti/work1/6208045574d6b85d/artifactory/Subproduct/2019.1/Subproduct.war'
```

**Comment by DimaNevelev** [comment]
@daveneeley, 
I did not manage to reproduce this issue. I used our latest plugin version (2.7.1) and the official docker images: "jetbrains/teamcity-server:2018.1.2" and "jetbrains/teamcity-agent:2018.1.2"
Do you have any Idea how can I reproduce it?

**Comment by daveneeley** [comment]
@DimaNevelev the best guess I have is that it is a certificate chain problem? It reproduces consistently on one particular build machine, but I have no idea what makes that machine different.

**Comment by thedarkdestructor** [comment]
Hi @daveneeley. We had exactly the same problem and then we figured out that the issue was that the agent was running with java 1.7 but the new versions of the plugin requires java 1.8. We found out this looking at the agent build log were we found the following 

`[2019-02-19 17:27:23,072]   INFO -    jetbrains.buildServer.AGENT - Publishing artifacts process finished`

--> Upgrading the agent jre to java8 solved the issue.

Hope this helps

**Comment by daveneeley** [comment]
I was hopeful, but the agent is running java 1.8 jdk. Thank you for the suggestion.

**Comment by testworksau** [comment]
We're using version `2018.2.4` of TeamCity and `2.8.0` of the Artifactory plugin, and are seeing the same issue.

```
[2019-05-23 14:11:30,684]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.runnerFinished for listener org.jfrog.teamcity.agent.ArtifactoryAgentListener: java.lang.NullPointerException
Error calling method AgentLifeCycleListener.runnerFinished for listener org.jfrog.teamcity.agent.ArtifactoryAgentListener: java.lang.NullPointerException
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:148)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:122)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:72)
	at com.sun.proxy.$Proxy8.runnerFinished(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.finish.FireRunnerFinishedFStage.doFinishStage(FireRunnerFinishedFStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.runFinishStage(RunnerFinishStagesExecutor.java:32)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.doBuildFinishStages(RunnerFinishStagesExecutor.java:23)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.safeCallFinishStages(RunnerContextExecutor.java:65)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:56)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:300)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:54)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jfrog.teamcity.agent.ArtifactoryAgentLifeCycleAdapter.addBuildInfoUrlParam(ArtifactoryAgentLifeCycleAdapter.java:29)
	at org.jfrog.teamcity.agent.ArtifactoryAgentLifeCycleAdapter.runnerFinished(ArtifactoryAgentLifeCycleAdapter.java:22)
	at org.jfrog.teamcity.agent.ArtifactoryAgentListener.runnerFinished(ArtifactoryAgentListener.java:109)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:128)
	... 25 more
[2019-05-23 14:11:30,685]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.runnerFinished for listener org.jfrog.teamcity.agent.ivy.IvyBuildInfoAgentListener: java.lang.NullPointerException
Error calling method AgentLifeCycleListener.runnerFinished for listener org.jfrog.teamcity.agent.ivy.IvyBuildInfoAgentListener: java.lang.NullPointerException
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:148)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:122)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:72)
	at com.sun.proxy.$Proxy8.runnerFinished(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.finish.FireRunnerFinishedFStage.doFinishStage(FireRunnerFinishedFStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.runFinishStage(RunnerFinishStagesExecutor.java:32)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.doBuildFinishStages(RunnerFinishStagesExecutor.java:23)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.safeCallFinishStages(RunnerContextExecutor.java:65)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:56)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:300)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:54)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jfrog.teamcity.agent.ArtifactoryAgentLifeCycleAdapter.addBuildInfoUrlParam(ArtifactoryAgentLifeCycleAdapter.java:29)
	at org.jfrog.teamcity.agent.ArtifactoryAgentLifeCycleAdapter.runnerFinished(ArtifactoryAgentLifeCycleAdapter.java:22)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:128)
	... 25 more
[2019-05-23 14:11:30,685]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.runnerFinished for listener org.jfrog.teamcity.agent.gradle.GradleBuildInfoAgentListener: java.lang.NullPointerException
Error calling method AgentLifeCycleListener.runnerFinished for listener org.jfrog.teamcity.agent.gradle.GradleBuildInfoAgentListener: java.lang.NullPointerException
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:148)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:122)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:72)
	at com.sun.proxy.$Proxy8.runnerFinished(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.runnerStages.finish.FireRunnerFinishedFStage.doFinishStage(FireRunnerFinishedFStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.runFinishStage(RunnerFinishStagesExecutor.java:32)
	at jetbrains.buildServer.agent.impl.buildStages.RunnerFinishStagesExecutor.doBuildFinishStages(RunnerFinishStagesExecutor.java:23)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.safeCallFinishStages(RunnerContextExecutor.java:65)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:56)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:300)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:54)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:264)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.jfrog.teamcity.agent.ArtifactoryAgentLifeCycleAdapter.addBuildInfoUrlParam(ArtifactoryAgentLifeCycleAdapter.java:29)
	at org.jfrog.teamcity.agent.ArtifactoryAgentLifeCycleAdapter.runnerFinished(ArtifactoryAgentLifeCycleAdapter.java:22)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:128)
	... 25 more
```

**Comment by yaegor** [comment]
(got hold of another log with the NPE)

Looking into the code, it seems that the issue will reproduce when there is 
org.jfrog.artifactory.selectedDeployableServer.publishBuildInfo
parameter defined in the runner settings, but there is no org.jfrog.artifactory.selectedDeployableServer.url
parameter.

This should be handled by the plugin as step parameters can be set via REST, Kotlin DSL, etc. and can appear in any state in the build configuration settings.

Seems like ArtifactoryAgentLifeCycleAdapter.addBuildInfoUrlParam needs to be updated to support case when no url parameter is present.
