### ISSUE TITLE
TeamCity pending changes trigger issue

### ISSUE THREAD

**Issue by twalker-illumina** [jfrog/teamcity-artifactory-plugin#95]
Occasionally, the thread that is responsible for processing build triggers gets blocked by the teamcity-artifactory-plugin plugin. The plugin implements a trigger called ArtifactoryPolledBuildTrigger. This trigger tries to initiate an HTTP connection to an external resource during its work. The problem is, looks like there is no timeout set for the connection. In the below stacktrace, the plugin locked the Build triggers executor 1 thread for 24 minutes. TC didn't poll other triggers while this thread was locked.
You should reach out to the plugin developer with this. If the logic cannot be moved elsewhere, they should at least add a timeout for this connection. But keep in mind, that even with a timeout, processing for other triggers may often be delayed. A workaround is to disable the plugin until the problem is fixed, but I presume you use it quite heavily.
Build triggers executor 1
  24m:20s Task: 'java.util.concurrent.CompletableFuture$AsyncRun@42de68af'
    24m:20s Processing 2237 build trigger groups (total parts: #1)
      24m:13s Processing build triggers group 1799/2237 for build type with id P10_DemoBuildChainProject_ArtifactoryTest with 2 triggers
        24m:13s Executing TriggerDescriptor{id='TRIGGER_234', name='artifactory'} of Digital Transformation / DEMO BUILD CHAIN PROJECT / ARTIFACTORY-TEST {id=P10_DemoBuildChainProject_ArtifactoryTest, internal id=bt4461}
Show/hide stacktrace »
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:607)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:338)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:84)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:88)
at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.getItemLastModified(ArtifactoryBuildInfoClient.java:324)
at org.jfrog.teamcity.server.trigger.ArtifactoryPolledBuildTrigger.triggerPolling(ArtifactoryPolledBuildTrigger.java:141)
at org.jfrog.teamcity.server.trigger.ArtifactoryPolledBuildTrigger.triggerBuild(ArtifactoryPolledBuildTrigger.java:91)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.lambda$callTrigger$12(BuildTriggersChecker.java:2)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$$Lambda$1780/1670712239.run(Unknown Source)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:489)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$2800(BuildTriggersChecker.java:418)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:77)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$$Lambda$1776/749863617.run(Unknown Source)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.lambda$null$7(BuildTriggersChecker.java:492)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$$Lambda$1775/680362760.run(Unknown Source)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.lambda$triggerBuildsBySpecifiedTypes$8(BuildTriggersChecker.java:243)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$$Lambda$1773/2117807421.run(Unknown Source)
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by twalker-illumina** [comment]
Follow up with comments from JetBrains support:

Re: Pending changes delay triggering build over 20 minutes

Walker, Terry
Thursday at 09:45
This is a follow-up to your previous request #3332799 "Pending changes delay triggering build over 20 minutes"
We have a response from the engineers at Jfrog and wanted to run that by you. According to jfrog they use.
https://javadoc.jetbrains.net/teamcity/openapi/current/jetbrains/buildServer/buildTriggers/async/package-summary.html
AsyncPolledBuildTrigger
But, based on their github:
https://github.com/jfrog/teamcity-artifactory-plugin/blob/master/server/src/main/java/org/jfrog/teamcity/server/trigger/ArtifactoryPolledBuildTrigger.java#L46
They use
PolledBuildTrigger instead
Is their implementation wrong? Shouldn't they be using what they “THINK” they're using rather than what they actually are?
Thanks,
Terry

Walker, Terry
Thursday at 09:47
Using PolledBuildTrigger.java would result in sequential triggers and be the root of the problem as you pointed out in the earlier ticket, correct?

Mikhail Efremov
Yesterday at 06:07
Hello Terry,
I don't think I ever mentioned either AsyncPolledBuildTrigger or PolledBuildTrigger at all; that's quite an investigation you have performed.
But yeah, you are right. Using Async trigger instead of a regular one can help prevent other builds from being delayed. This way, a single trigger will not block the entire Build triggers executor thread, so other triggers will be able to continue their work.
The root problem here, however, is that the implementation of HTTPS connection remains inside of the trigger's logic. Until this logic is moved elsewhere or a timeout is implemented, builds that have this trigger can take longer to start as the trigger will still have to connect to an external resource. A timeout is mandatory in any case, even if the logic is moved elsewhere. Not having a timeout on your connections is usually bad practice.
Allow me also to elaborate on the 'move the logic elsewhere' approach. They can implement a service that works with an external resource as part of their plugin. It can periodically request and store the corresponding data. The trigger will just have to ask this service for the data. This way, there will be no connections to external resources inside the trigger logic at all.
Best regards,
Mikhail Efremov
JetBrains | TeamCity

**Comment by shuvadipc** [comment]
Outdated.
